server:
  # 로컬 작업 시
 address: localhost
 port: 8888
  # AWS 서버 작업 시 (port 만 사용)
  # port: 8085
 servlet:
  context-path: /

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://i8d106.p.ssafy.io:3306/naegagalga?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8
    username: ssafyD106
    password: ssafycommonD106
  #    url: jdbc:mysql://stg-yswa-kr-practice-db-master.mariadb.database.azure.com:3306/S08P12D106?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
  #    username: S08P12D106@stg-yswa-kr-practice-db-master
  #    password: w2TFbH3C22

  #    url: jdbc:mysql://localhost:3306/pjt?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
  #    username: test
  #    password: Abcd123!

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  profiles:
    include: key

  redis:
    host: i8d106.p.ssafy.io
    port: 6379
